// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package hikedb

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID          int32        `json:"id"`
	PostID      int32        `json:"post_id"`
	UserID      int32        `json:"user_id"`
	CommentText string       `json:"comment_text"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   sql.NullTime `json:"updatedAt"`
}

type Route struct {
	ID          int32        `json:"id"`
	AdminID     int32        `json:"admin_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Location    string       `json:"location"`
	Destination float64      `json:"destination"`
	Height      float64      `json:"height"`
	Level       string       `json:"level"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   sql.NullTime `json:"updatedAt"`
}

type User struct {
	ID                int32     `json:"id"`
	Username          string    `json:"username"`
	Age               int32     `json:"age"`
	Email             string    `json:"email"`
	Password          string    `json:"password"`
	Role              string    `json:"role"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"createdAt"`
}
