CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "age" int NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "role" varchar NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT (now()),
  "updatedAt" timestamp
);

CREATE TABLE "routes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "location" varchar NOT NULL,
  "destination" float NOT NULL,
  "height" float NOT NULL,
  "level" varchar NOT NULL,
  "createdAt" timestamp NOT NULL,
  "updatedAt" timestamp
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "comment_text" text NOT NULL,
  "createdAt" timestamp NOT NULL,
  "updatedAt" timestamp
);

ALTER TABLE "routes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "routes" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
